freeslot("SKINCOLOR_LEGENDARYSUPERSAIYAN")
skincolors[SKINCOLOR_LEGENDARYSUPERSAIYAN] = {
    name = "LegendarySuperSaiyan",
    ramp = {80,80,88,88,96,97,98,113,114,115,116,117,118,119,111,31},
    invcolor = SKINCOLOR_LIME,
    invshade = 9,
    chatcolor = V_GREENMAP,
    accessible = true
}

freeslot("SKINCOLOR_SUPERSAIYANGOD")
skincolors[SKINCOLOR_SUPERSAIYANGOD] = {
    name = "SuperSaiyanGod",
    ramp = {209,210,32,34,35,36,39,42,44,45,71,46,47,47,30,31},
    invcolor = SKINCOLOR_FLAME,
    invshade = 9,
    chatcolor = V_REDMAP,
    accessible = true
}

freeslot("SKINCOLOR_SUPERSAIYANBLUE")
skincolors[SKINCOLOR_SUPERSAIYANBLUE] = {
    name = "SuperSaiyanBlue",
    ramp = {128,129,130,131,132,141,141,142,137,137,138,138,139,139,29,31},
    invcolor = SKINCOLOR_RED,
    invshade = 9,
    chatcolor = V_SKYMAP,
    accessible = true
}

freeslot("SKINCOLOR_SUPERSAIYANBLUEEVOLUTION")
skincolors[SKINCOLOR_SUPERSAIYANBLUEEVOLUTION] = {
    name = "SuperSaiyanBlueEvolution",
    ramp = {0,128,129,131,133,135,153,154,155,156,157,158,253,254,254,31},
    invcolor = SKINCOLOR_SAPPHIRE,
    invshade = 9,
    chatcolor = V_BLUEMAP,
    accessible = true
}

freeslot("SKINCOLOR_SUPERSAIYANROSE")
skincolors[SKINCOLOR_SUPERSAIYANROSE] = {
    name = "SuperSaiyanRose",
    ramp = {0,252,176,201,202,202,33,34,34,34,38,39,41,42,44,45},
    invcolor = SKINCOLOR_RASPBERRY,
    invshade = 9,
    chatcolor = V_ROSYMAP,
    accessible = true
}

freeslot("SKINCOLOR_ULTRAINSTINCT")
skincolors[SKINCOLOR_ULTRAINSTINCT] = {
    name = "UltraInstinct",
    ramp = {0,1,1,2,3,5,8,13,17,172,173,173,174,175,175,31},
    invcolor = SKINCOLOR_BLUE,
    invshade = 9,
    chatcolor = V_WHITEMAP,
    accessible = true
}